#!/usr/bin/env python3
"""Regenerate game/src/meta/missions_embed.h from game/data/missions.json.
The embedded copy is the fallback campaign when the data file is missing or broken."""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, "game/data/missions.json")
txt = open(src, encoding="utf-8").read()
json.loads(txt)  # refuse to embed broken JSON
compact = json.dumps(json.loads(txt), separators=(",", ":"), ensure_ascii=True)
out = ["/* GENERATED by tools/gen_embed.py from game/data/missions.json - do not edit */",
       "#ifndef DH_MISSIONS_EMBED_H", "#define DH_MISSIONS_EMBED_H",
       "static const char MISSIONS_EMBED[] ="]
for i in range(0, len(compact), 100):
    chunk = compact[i:i+100].replace("\\", "\\\\").replace('"', '\\"')
    out.append('    "' + chunk + '"')
out[-1] += ";"
out.append("#endif")
open(os.path.join(root, "game/src/meta/missions_embed.h"), "w").write("\n".join(out) + "\n")
print("embedded", len(compact), "bytes")
